#!/bin/sh
set -eu
psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set ON_ERROR_STOP=1 <<'SQL'
\getenv server_password KZ_SERVER_DATABASE_PASSWORD
CREATE ROLE keyzori_server LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD :'server_password';
REVOKE ALL ON DATABASE keyzori FROM PUBLIC;
GRANT CONNECT ON DATABASE keyzori TO keyzori_server;
ALTER SCHEMA public OWNER TO keyzori_server;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
CREATE SCHEMA drizzle AUTHORIZATION keyzori_server;
REVOKE ALL ON SCHEMA drizzle FROM PUBLIC;
ALTER ROLE keyzori_server SET search_path = public, pg_catalog;
ALTER DEFAULT PRIVILEGES FOR ROLE keyzori_server IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE keyzori_server IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC;
SQL
