export const webhookEvents = [
	"license.created",
	"license.updated",
	"license.enabled",
	"license.disabled",
	"license.deleted",
	"license.rotated",
	"user.created",
	"user.updated",
	"user.enabled",
	"user.disabled",
	"user.deleted",
	"item.created",
	"item.updated",
	"item.enabled",
	"item.disabled",
	"item.deleted",
	"meter.limit_reached",
	"meter.reset",
	"validation.failed",
] as const;
