import type { RequestService } from "../core/http/RequestService";
import type { ApiKeyService } from "../plugins/api-keys/ApiKeyService";
import type { HealthService } from "../plugins/health/HealthService";
import type { ItemService } from "../plugins/items/ItemService";
import type { LicenseService } from "../plugins/licenses/LicenseService";
import type { SettingsService } from "../plugins/settings/SettingsService";
import type { UserService } from "../plugins/users/UserService";
import type { ValidationService } from "../plugins/validate/ValidationService";
import type { WebhookService } from "../plugins/webhooks/WebhookService";

export type $Requests = Pick<RequestService, "authorize" | "runtime">;
export type $ApiKeys = Pick<ApiKeyService, keyof ApiKeyService>;
export type $Health = Pick<HealthService, "status">;
export type $Items = Pick<ItemService, keyof ItemService>;
export type $Licenses = Pick<LicenseService, keyof LicenseService>;
export type $Settings = Pick<SettingsService, "read" | "update">;
export type $Users = Pick<UserService, keyof UserService>;
export type $Validation = Pick<ValidationService, "validate">;
export type $Webhooks = Pick<WebhookService, keyof WebhookService>;
export type $ApplicationServices = {
	requests: $Requests;
	apiKeys: $ApiKeys;
	health: $Health;
	items: $Items;
	licenses: $Licenses;
	settings: $Settings;
	users: $Users;
	validation: $Validation;
	webhooks: $Webhooks;
};
