export const openApiDescription = [
	"Keyzori validates and manages software licenses. Licensed products use the `/v1/*` runtime API; instance operators use the authenticated `/admin/*` API or local CLI.",
	"",
	"## Runtime API",
	"",
	"| Route | Purpose |",
	"| --- | --- |",
	"| `POST /v1/activate` | Validate `{ licenseKey, deviceId }` once and create an IP/device-bound session. |",
	"| `POST /v1/heartbeat` | Revalidate policy and refresh `{ sessionToken, deviceId }`. |",
	"| `POST /v1/usage` | Atomically debit `{ sessionToken, deviceId, meter, units, eventId }`. |",
	"| `POST /v1/deactivate` | Idempotently release `{ sessionToken, deviceId }`. |",
	"",
	"Activation and heartbeat return `licenseType`, client-visible `metadata`, a server-issued `sessionToken`, and `sessionTtlSeconds`. Only activation accepts the full license secret. Usage requires positive integer units and a per-license idempotency `eventId`; an identical retry returns the original result and conflicting reuse returns `USAGE_EVENT_CONFLICT`.",
	"",
	"Stable runtime error codes are `INVALID_REQUEST`, `LICENSE_INVALID`, `LICENSE_REVOKED`, `LICENSE_EXPIRED`, `IP_NOT_ALLOWED`, `DEVICE_NOT_ALLOWED`, `SESSION_INVALID_OR_EXPIRED`, `CONCURRENT_SESSION_LIMIT`, `METER_NOT_FOUND`, `METER_ARCHIVED`, `METER_EXHAUSTED`, `USAGE_EVENT_CONFLICT`, `IP_REGISTRATION_LIMIT`, `DEVICE_REGISTRATION_LIMIT`, `RATE_LIMITED`, and `INTERNAL_ERROR`.",
	"",
	"## License model",
	"",
	"Create licenses with `POST /admin/licenses`. Common fields are `customerId`, `type`, `maxIps`, `maxDevices`, `maxSessions`, and `metadata`. Zero means unlimited for the three maximums.",
	"",
	"| Type | Required behavior |",
	"| --- | --- |",
	"| `lifetime` | No type-level expiry or usage balance. |",
	"| `subscription` | Requires a future `expiresAt`; supports manual renewal and optional Stripe synchronization. |",
	"| `metered` | Requires at least one named integer meter; only explicit usage calls debit it. |",
	"| `trial` | Requires positive `trialDurationMinutes`; starts on first activation. |",
	"",
	"Type changes preserve the secret, customer, common limits, allowlists, and registered devices and apply on the next runtime request. Type-specific settings remain in `typeDrafts`. Effective status is derived as `active`, `expired`, or `revoked`, with a reason when applicable.",
	"",
	"The complete `licenseKey` is returned only by successful creation and `POST /admin/licenses/:id/actions/rotate-key`. Every other response exposes only `keyPrefix`. New secrets begin with `lic_` and cannot be reconstructed from storage.",
	"",
	"## Operator API",
	"",
	"All `/admin/*` routes require `X-Admin-Key`.",
	"",
	"- Customers: `POST /admin/customers`, `GET /admin/customers`, `GET /admin/customers/:id`, `PATCH /admin/customers/:id`, and `DELETE /admin/customers/:id`.",
	"- Licenses: `POST /admin/licenses`, `GET /admin/licenses`, `GET /admin/licenses/:id`, `PATCH /admin/licenses/:id`, and `DELETE /admin/licenses/:id`.",
	"- Actions: `POST /admin/licenses/:id/actions/renew`, `POST /admin/licenses/:id/actions/revoke`, `POST /admin/licenses/:id/actions/restore`, `POST /admin/licenses/:id/actions/rotate-key`, `POST /admin/licenses/:id/actions/terminate-sessions`, and `POST /admin/licenses/:id/actions/reset-devices`.",
	"- Access: `GET /admin/licenses/:id/access`; `POST /admin/licenses/:id/allowlists/ips`; `DELETE /admin/licenses/:id/allowlists/ips/:ip`; `POST /admin/licenses/:id/allowlists/devices`; `DELETE /admin/licenses/:id/allowlists/devices/:deviceId`; `DELETE /admin/licenses/:id/registrations/ips/:ip`; and `DELETE /admin/licenses/:id/registrations/devices/:deviceId`.",
	"- Meters: `GET /admin/licenses/:id/meters`; `POST /admin/licenses/:id/meters`; `POST /admin/licenses/:id/meters/:name/actions/archive`; `POST /admin/licenses/:id/meters/:name/actions/top-up`; `POST /admin/licenses/:id/meters/:name/actions/adjust`; and `GET /admin/licenses/:id/usage-ledger`.",
	"- Telemetry: `GET /admin/activity` and `GET /admin/statistics`, filterable by license, customer, event type, time range, and result limit.",
	"",
	"Explicit allowlists are separate from registered IP/device slots. Adding the first allowlist entry makes that dimension restrictive. Meter names are immutable; archival and every operator balance change are recorded in the usage ledger with a reason.",
	"",
	"## Optional Stripe API",
	"",
	"When both Stripe secrets are configured, operators can use `GET /admin/licenses/:id/stripe`, `POST /admin/licenses/:id/actions/link-stripe`, `POST /admin/licenses/:id/actions/unlink-stripe`, and `POST /admin/licenses/:id/actions/sync-stripe`. The signed raw-body endpoint is `POST /webhooks/stripe`. Stripe never exposes license controls to customers and Keyzori does not create Checkout or portal sessions.",
	"",
	"## Deployment configuration",
	"",
	"| Variable | Required/default | Meaning |",
	"| --- | --- | --- |",
	"| `KEYZORI_DATABASE_URL` | Required | PostgreSQL connection URL. |",
	"| `KEYZORI_REDIS_URL` | Required | Redis connection URL for runtime sessions and rate limits. |",
	"| `KEYZORI_ADMIN_PASS` | Required | Admin password sent through the `X-Admin-Key` header. |",
	"| `KEYZORI_SERVER_HOST` | `0.0.0.0` | HTTP listen address. |",
	"| `KEYZORI_SERVER_PORT` | `3000` | HTTP listen port. |",
	"| `KEYZORI_STRIPE_SECRET_KEY` | Optional pair | Enables Stripe only when the webhook secret is also set. |",
	"| `KEYZORI_STRIPE_WEBHOOK_SECRET` | Optional pair | Required with the Stripe secret key; partial configuration fails startup. |",
	"| `KEYZORI_EVENT_RETENTION_DAYS` | `30` | Detailed activity retention from 1 to 365 days. |",
	"| `KEYZORI_TRUST_PROXY_HEADERS` | `false` | Trust forwarded client IPs only through configured proxy networks. |",
	"| `KEYZORI_TRUSTED_PROXY_HEADER` | `x-forwarded-for` | `x-forwarded-for`, `cf-connecting-ip`, `x-real-ip`, or fail-closed `*` selection. |",
	"| `KEYZORI_TRUSTED_PROXY_CIDRS` | Conditional | Immediate trusted proxy CIDRs, or `*`. |",
	"| `KEYZORI_OPENAPI_ENABLED` | `true` | Enable this UI and `/docs/openapi.json`. |",
	"| `KEYZORI_RATE_LIMIT_PER_MINUTE` | `60` | Admin requests per source IP per minute. |",
	"| `KEYZORI_LICENSE_RATE_LIMIT_PER_MINUTE` | `30` | Runtime requests per hashed principal, per endpoint, per minute. Usage bursts cannot consume heartbeat or deactivation capacity. |",
	"| `KEYZORI_RATE_LIMIT_PER_IP_PER_MINUTE` | `6000` | Coarse application-route IP ceiling. |",
	"| `KEYZORI_MAX_REQUEST_BODY_BYTES` | `65536` | JSON request body ceiling. |",
].join("\n");
